name: interface
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: aga <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  html: ^0.13.3+3
  path: ^1.6.2

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
